version: '3.4'

services:
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  dapr_zipkin:
    image: openzipkin/zipkin-slim:latest
    ports:
      - "9411:9411"

  dapr_placement:
    command: ["./placement", "-port", "50000", "-log-level", "debug"]
    ports:
      - "50000:50000"

  dapr_dashboard:
    command: [
      "dapr",
      "dashboard",
      "--dapr-http-port", "9999"
      # "--dapr-grpc-port", "50001"
    ]
    ports:
      - "9999:8080"
      # - "50001:50001"
   
  bcommerce.httpaggregator:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  bcommerce.dapr.api:
    environment:
      - ENVOY_COMMON_API_ADDRESS=bcommerce.commonservice.api
      - ENVOY_COMMON_API_PORT=80
      - ENVOY_MASTER_API_ADDRESS=bcommerce.masterservice.api
      - ENVOY_MASTER_API_PORT=80
    ports:
      - "5202:80"
      # - "15202:8001"
      - "50008:50001"

  bcommerce-dapr-api-dapr:
    # network_mode: "service:bcommerce.dapr.api"
    command: [
      "./daprd",
      "--app-id", "dapr-client",
      "--app-port", "5001",
      "--dapr-http-port", "50001",
      "--resources-path", "./components",
       "-components-path", "./components",
      "-config", "./components/config.yaml"
     ]
    volumes:
        - "./components/:/components"

  bcommerce.commonservice.api:
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
        - "5101:80"
        - "50002:50001"

  bcommerce-commonservice-api-dapr:
    command: [
      "./daprd",
      "--app-id", "commonapi",
      "--app-port", "5002",
      "--dapr-http-port", "50002",
      "--resources-path", "./components",
       "-components-path", "./components",
      "-config", "./components/config.yaml"
     ]
    volumes:
        - "./components/:/components"

  bcommerce.masterservice.api:
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
        - "5102:80"
        - "50003:50001"

  bcommerce-masterservice-api-dapr:
    command: [
      "./daprd",
      "--app-id", "masterapi",
      "--app-port", "5003",
      "--dapr-http-port", "50003",
      "--resources-path", "./components",
       "-components-path", "./components",
      "-config", "./components/config.yaml"
      ]
    volumes:
      - "./components/:/components"

  bcommerce.airlineservice.api:
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
        - "5103:80"
        - "50004:50001"

  bcommerce-airlineservice-api-dapr:
    command: [
      "./daprd",
      "--app-id", "airlineapi",
      "--app-port", "5004",
      "--dapr-http-port", "50004",
      "--resources-path", "./components",
       "-components-path", "./components",
      "-config", "./components/config.yaml"
     ]
    volumes:
        - "./components/:/components"

volumes:
  postgres-data: