apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprConfig
spec:
  http:
    port: 8080
  grpc:
    port: 50001
  tracing:
    # enabled: true
    # expandParams: true
    # includeBody: true
    samplingRate: "1"
    zipkin:
      endpointAddress: http://localhost:9411/api/v2/spans